// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['app']['ClusterAPI']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['ClusterAPI']['Disconnect'](arg1);
}

export function List() {
  return window['go']['app']['ClusterAPI']['List']();
}
