// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Targets(arg1) {
  return window['go']['app']['ContainerAPI']['Targets'](arg1);
}
