// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Targets(arg1:domain.ResourceRef):Promise<Array<domain.ContainerTarget>>;
