// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Refresh(arg1) {
  return window['go']['app']['DiscoveryAPI']['Refresh'](arg1);
}

export function Resources(arg1) {
  return window['go']['app']['DiscoveryAPI']['Resources'](arg1);
}
