// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Refresh(arg1:string):Promise<Array<domain.APIResource>>;

export function Resources(arg1:string):Promise<Array<domain.APIResource>>;
