// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NodeShell(arg1, arg2, arg3, arg4) {
  return window['go']['app']['ExecAPI']['NodeShell'](arg1, arg2, arg3, arg4);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['app']['ExecAPI']['Resize'](arg1, arg2, arg3);
}

export function Send(arg1, arg2) {
  return window['go']['app']['ExecAPI']['Send'](arg1, arg2);
}

export function Start(arg1, arg2, arg3, arg4) {
  return window['go']['app']['ExecAPI']['Start'](arg1, arg2, arg3, arg4);
}

export function Stop(arg1) {
  return window['go']['app']['ExecAPI']['Stop'](arg1);
}
