// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function NodeShell(arg1:string,arg2:string,arg3:string,arg4:domain.ExecOptions):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Send(arg1:string,arg2:string):Promise<void>;

export function Start(arg1:string,arg2:string,arg3:domain.ContainerTarget,arg4:domain.ExecOptions):Promise<void>;

export function Stop(arg1:string):Promise<void>;
