// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Detail(arg1, arg2) {
  return window['go']['app']['HelmAPI']['Detail'](arg1, arg2);
}

export function History(arg1) {
  return window['go']['app']['HelmAPI']['History'](arg1);
}

export function Releases(arg1) {
  return window['go']['app']['HelmAPI']['Releases'](arg1);
}

export function Rollback(arg1, arg2) {
  return window['go']['app']['HelmAPI']['Rollback'](arg1, arg2);
}

export function Uninstall(arg1) {
  return window['go']['app']['HelmAPI']['Uninstall'](arg1);
}
