// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Detail(arg1:domain.HelmRef,arg2:number):Promise<domain.HelmDetail>;

export function History(arg1:domain.HelmRef):Promise<Array<domain.HelmRelease>>;

export function Releases(arg1:string):Promise<Array<domain.HelmRelease>>;

export function Rollback(arg1:domain.HelmRef,arg2:number):Promise<void>;

export function Uninstall(arg1:domain.HelmRef):Promise<void>;
