// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['app']['KubeconfigAPI']['Add'](arg1);
}

export function Import(arg1) {
  return window['go']['app']['KubeconfigAPI']['Import'](arg1);
}

export function List() {
  return window['go']['app']['KubeconfigAPI']['List']();
}

export function Pick() {
  return window['go']['app']['KubeconfigAPI']['Pick']();
}

export function Remove(arg1) {
  return window['go']['app']['KubeconfigAPI']['Remove'](arg1);
}
