// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Add(arg1:string):Promise<Array<domain.KubeconfigFile>>;

export function Import(arg1:string):Promise<domain.KubeconfigFile>;

export function List():Promise<Array<domain.KubeconfigFile>>;

export function Pick():Promise<string>;

export function PickFolder():Promise<string>;

export function Remove(arg1:string):Promise<void>;
