// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Start(arg1, arg2, arg3, arg4) {
  return window['go']['app']['LogAPI']['Start'](arg1, arg2, arg3, arg4);
}

export function Stop(arg1) {
  return window['go']['app']['LogAPI']['Stop'](arg1);
}

export function Targets(arg1) {
  return window['go']['app']['LogAPI']['Targets'](arg1);
}
