// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Start(arg1:string,arg2:string,arg3:domain.LogTarget,arg4:domain.LogOptions):Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function Targets(arg1:domain.ResourceRef):Promise<Array<domain.LogTarget>>;
