// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function PodSample(arg1:string,arg2:string,arg3:string):Promise<domain.PodUsage>;

export function Sample(arg1:string):Promise<domain.MetricsSample>;
