// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List() {
  return window['go']['app']['PortForwardAPI']['List']();
}

export function Ports(arg1) {
  return window['go']['app']['PortForwardAPI']['Ports'](arg1);
}

export function Start(arg1, arg2, arg3) {
  return window['go']['app']['PortForwardAPI']['Start'](arg1, arg2, arg3);
}

export function Stop(arg1) {
  return window['go']['app']['PortForwardAPI']['Stop'](arg1);
}
