// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Subscribe(arg1:string,arg2:string,arg3:domain.GVR,arg4:string):Promise<domain.Subscription>;

export function Unsubscribe(arg1:string):Promise<void>;
