// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Subscribe(arg1, arg2, arg3, arg4) {
  return window['go']['app']['ResourceAPI']['Subscribe'](arg1, arg2, arg3, arg4);
}

export function Unsubscribe(arg1) {
  return window['go']['app']['ResourceAPI']['Unsubscribe'](arg1);
}
