// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1, arg2) {
  return window['go']['app']['ResourceAPI']['Apply'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['ResourceAPI']['Delete'](arg1);
}

export function Events(arg1) {
  return window['go']['app']['ResourceAPI']['Events'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['ResourceAPI']['Get'](arg1);
}

export function Owners(arg1) {
  return window['go']['app']['ResourceAPI']['Owners'](arg1);
}

export function Scale(arg1, arg2) {
  return window['go']['app']['ResourceAPI']['Scale'](arg1, arg2);
}

export function Subscribe(arg1, arg2, arg3, arg4) {
  return window['go']['app']['ResourceAPI']['Subscribe'](arg1, arg2, arg3, arg4);
}

export function Unsubscribe(arg1) {
  return window['go']['app']['ResourceAPI']['Unsubscribe'](arg1);
}
