// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Apply(arg1:domain.ResourceRef,arg2:Record<string, any>):Promise<Record<string, any>>;

export function Delete(arg1:domain.ResourceRef):Promise<void>;

export function Events(arg1:domain.ResourceRef):Promise<Array<domain.EventRecord>>;

export function Get(arg1:domain.ResourceRef):Promise<Record<string, any>>;

export function Owners(arg1:domain.ResourceRef):Promise<Array<domain.OwnerRef>>;

export function Scale(arg1:domain.ResourceRef,arg2:number):Promise<void>;

export function Subscribe(arg1:string,arg2:string,arg3:domain.GVR,arg4:string):Promise<domain.Subscription>;

export function Unsubscribe(arg1:string):Promise<void>;
