// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir():Promise<string>;

export function Fonts():Promise<Array<string>>;

export function Reveal(arg1:string):Promise<void>;

export function Version():Promise<string>;
