// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir() {
  return window['go']['app']['SettingsAPI']['Dir']();
}

export function Fonts() {
  return window['go']['app']['SettingsAPI']['Fonts']();
}

export function Reveal(arg1) {
  return window['go']['app']['SettingsAPI']['Reveal'](arg1);
}

export function Version() {
  return window['go']['app']['SettingsAPI']['Version']();
}
