// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['app']['UpdateAPI']['Check']();
}

export function Install() {
  return window['go']['app']['UpdateAPI']['Install']();
}

export function OpenRelease() {
  return window['go']['app']['UpdateAPI']['OpenRelease']();
}
