// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Check():Promise<domain.UpdateStatus>;

export function Install():Promise<void>;

export function OpenRelease():Promise<void>;
